### PR TITLE
Ft mapbox

### PR DESCRIPTION
**Pull request by Ariuka11**
## Description
Displays mapbox and directions from the About us section on the navbar 
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
## Link to Trello card
https://trello.com/c/q9emPRLy/97-sends-coordinates-from-the-frontend-to-the-backend-mapbox

### CODE REVIEW

**Review by mjedwards — DISMISSED** [review]
The "About Us" in the StoreNav bar does not work. Also we need a new Google API key, we must remove the current one being used.

**Review by mjedwards — CHANGES_REQUESTED** [review]
Remove current Google API key and replace it with one that designated for this project

**Comment by Ariuka11** [comment]
> Remove current Google API key and replace it with one that designated for this project

I changed the Google API key.

**Comment by Ariuka11** [comment]
> The "About Us" in the StoreNav bar does not work. Also we need a new Google API key, we must remove the current one being used.

Did you do npm install before you start the app? Mine is working fine. Let me know if it is still not working

**Review by Cireimu — COMMENTED** [review]
We're getting there! That original error doesn't seem to be an issue, however now I'm getting this error:
cannot read property lat of null

**Review by mjedwards — DISMISSED** [review]

**Pull request merged**
