### PR TITLE
Ft  cart view

### PR DESCRIPTION
**Pull request by Ariuka11**
## Description
Describe change or new feature here.
Displays the variant options, variant name and concurrently updates the price accordingly in the singleProduct add to cart view. Total price is shown ,checkout button added and reflects the variant name and price in the cart view.
 ## Type of change
Added Total value and Checkout Button. Fixed duplicate item adding problem.
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
## Link to Trello card
https://trello.com/c/0MisfT79/83-cart-view

### CODE REVIEW

**Comment by bkandaris** [comment]
image
I think you meant to pass in cartID in the dispatch? (This fixed the error of savedCart not being defined

**Comment by Cireimu** [comment]
First thing I see is that you will need to do is pull from our develop branch and resolve merge conflicts (get in touch with me if you need help doing this

**Comment by Cireimu** [comment]
The second thing I need is for you to either fix the line that's erroring out for me and Ben or run us through your code and show us it works for you and then try to figure out what's wrong on our side.

**Comment by Cireimu** [comment]
Upon changing savedCart to cartID I am able to get into the app, but there is an issue with removing items from the cart

**Pull request merged**
