### PR TITLE
Ft  view add product  merge components

### PR DESCRIPTION
**Pull request by MatthewVaccaro**
## Description
The create product view that holds three components. *Add Photo*, *Basic Details* & *Add Variants*
## Type of change
New View
## Expected Actions

- [ ] Each component should have validation that clearly points to the correct input field
- [ ] Validation should be cleared once the info is added
- [ ] The view should be accessed on **http://localhost:3000/createItem**

## Link to Trello card
https://trello.com/c/lza9fYVA/63-create-product-view

### CODE REVIEW

**Comment by MatthewVaccaro** [comment]
[Create Product View](https://trello.com/c/lza9fYVA/63-create-product-view)

**Review by Cireimu — COMMENTED** [review]
Going through the code and the app, found a few things, first being two errors that appear on a product page on the storefront
Capture0000

**Comment by bkandaris** [comment]
Great work! This looks like a pretty complex component and I'm impressed! 

-There are a few console logs that could be cleaned up
-A console warning because the pictures don't have unique keys. Maybe try key={Date.now()} when mapping over the images to fix this?
-Receiving a '400 error' when doing the post?

Everything else seems to be working as intended. Pretty much just needs styling and whatever small thing fixed that is stopping the post request fixed.

**Review by Cireimu — DISMISSED** [review]

**Comment by MatthewVaccaro** [comment]
Everything should be fixed lads! Thank you for point this stuff out!

**Pull request merged**
