### PR TITLE
Ch  store regist form css

### PR DESCRIPTION
**Pull request by Ariuka11**
## Description
Updated welcome screen form UI.

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code

## Link to Trello card
https://trello.com/c/4OQUY2NP/113-store-registration-form-css

### CODE REVIEW

**Review by bkandaris — DISMISSED** [review]
This looks great! Good job!

**Review by Cireimu — CHANGES_REQUESTED** [review]
First off, I wanted to say a great job of getting the form up to a bigger size and looking clean in general. There are a few things I noted while looking through your application, first is that the "Add Information" Button is a wee bit too small and the text is extremely tiny, I need those to be updated. Seconded thing is that there no longer seems to be any sort of onSubmit on that button, so it's a dead form right now.

These are the main things I saw while going through it, but there might be more, later on, I also need you to pull from develop as well, since the rest of the app is quite out of date right now.

Small Button

**Comment by Ariuka11** [comment]
I fixed button functionality. But font-size looks normal on my branch.

**Comment by bkandaris** [comment]
> First off, I wanted to say a great job of getting the form up to a bigger size and looking clean in general. There are a few things I noted while looking through your application, first is that the "Add Information" Button is a wee bit too small and the text is extremely tiny, I need those to be updated. Seconded thing is that there no longer seems to be any sort of onSubmit on that button, so it's a dead form right now.
> 
> These are the main things I saw while going through it, but there might be more, later on, I also need you to pull from develop as well, since the rest of the app is quite out of date right now.
> 
> Small Button

There isn't supposed to be an onSubmit on this (Long story short back end issues didn't allow us to POST and then PUT because of CORS issues so the workaround POST was moved to the 'brandview/next screen' to just send the one single object and include that form data from welcome screen.

**Comment by bkandaris** [comment]
> I fixed button functionality. But font-size looks normal on my branch.

It was small on mine as well, I was thinking it was because you fixed the sizing on another branch though? Maybe after all these are merged we can re-assess and go from there.

**Comment by Cireimu** [comment]
Cool, looks good, I remember that work around you guys had to do, the button wasn't linked to the next component but now it is so we're all good! 

I just need you to pull from develop and we'll be all good. Button sizing still looks small, but maybe it gets fixed in another current PR that's waiting to get merged so we should be good with that.

**Review by Cireimu — APPROVED** [review]

**Pull request merged**
