### PR TITLE
Ch  admin navbar

### PR DESCRIPTION
**Pull request by Ariuka11**
## Description
Fixed Admin Navbar CSS
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
## Link to Trello card
https://trello.com/c/r4fnfuYZ/103-admin-nav-needs-css-fixes

### CODE REVIEW

**Comment by Cireimu** [comment]
Looks good no noticeable bugs, can you maybe add some responsiveness to the buttons and links in the navbar, also the images get too small when scaling down, so maybe having a min size would help with that.

**Review by Cireimu — DISMISSED** [review]
Once you pull from develop and resolve merge conflicts (with the app open) I will merge it. Good work Andy!

**Review by bkandaris — COMMENTED** [review]
No noticeable bugs, everything is working correctly.

There is some responsiveness issues. I see your commit message (Needs Burger Menu) so I wasn't sure if you were planning on implementing that on this PR. If not maybe throw it in as a 'chore' on Trello so we don't forget about it.
image

Maybe make the 'Pure Retail' Logo on the far left a link to the home page as well?

**Review by Cireimu — DISMISSED** [review]
Looks good, just need a re-review from one other person, as a final checkoff

**Review by Cireimu — APPROVED** [review]

**Pull request merged**
