### PR TITLE
Ft navbar

### PR DESCRIPTION
**Pull request by mjedwards**
## Description
fixed status options of order, and fixed links in Navbar, and fixed the order ids
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
expected)

## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Cireimu** [comment]
Can you please fill out the description and such? I have no idea what this is since it also has a generic title.

**Comment by Cireimu** [comment]
Looking at your PR now, the first thing I need you to do is pull from develop to stay up today and avoid any weird issues.

**Comment by Cireimu** [comment]
Looks good, no noticeable bugs from what I can tell.

**Review by Cireimu — APPROVED** [review]

**Review by erferguson — APPROVED** [review]
Code looks great. Easy to read and follow. Great job, Mike.

**Pull request merged**
