### PR TITLE
Ft  view add product -  add photo component

### PR DESCRIPTION
**Pull request by MatthewVaccaro**
## Description
Created the addPhoto Component to handle users adding photos to the product on the product creation page
## Type of change
New Feature

## Required Actions
[ ] Add Photo and display the photo
[ ] Remove photo when trash icon is clicked
[ ] Disabled "add photo button" after 3 photos have been added
[ ] Re-enable "add photo button" if a photo is removed

## Set Up Instructions
In-app JS uncomment the Import for the addPhoto component & the route at the bottom. The component is routed to work on localHost/testingGrounds

## Notes:
This component is not set up in the view currently - once it is we will use state to push props through to grab the current state held in the component.

### CODE REVIEW

**Comment by Cireimu** [comment]
[Addphoto Component](https://trello.com/c/4g8nW9wa/48-addphoto-component)

**Review by Cireimu — DISMISSED** [review]
Looks good and functions as expected. Just a few notes: 

1. On line 50 of your addPhoto component, it looks like you are trying to use await but it isn't actually being used, were you trying to make it an async call originally but figured out you didn't need it and forgot to remove all of the async await stuff, or are you still expecting it to be an async function. 

2. When adding photos for the first time I see `Warning: Each child in a list should have a unique "key" prop.` it doesn't seem to be negatively affecting anything as of right now, but might be something to keep a note on, or just get rid of the error by getting those items their keys. It seems to point to line 82 where the main div is.

**Comment by Cireimu** [comment]
One nitpick from me would be that we might want to have some sort of reaction for the "add photo" button to show that the component is being responsive, like having the cursor turn into a pointer on hover, again just a nitpick but thought I'd mention that.

**Comment by MatthewVaccaro** [comment]
[Addphoto Component](https://trello.com/c/4g8nW9wa/48-addphoto-component)

**Pull request merged**
