### PR TITLE
Ch  fix store front style

### PR DESCRIPTION
**Pull request by Ariuka11**
## Description
Mainly fixed the storefront font size issues and couple minor functionality bugs.
 
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project

## Link to Trello card
https://trello.com/c/J7wpGBBz/138-fix-css-in-store-front

### CODE REVIEW

**Review by Cireimu — DISMISSED** [review]
Looks good Andy.

**Review by Cireimu — DISMISSED** [review]

**Comment by bkandaris** [comment]
Looks good, Andy! The only things I noticed; 'variant' was spelled incorrectly on the inventory screen and the error messaging is still super tiny after logging into the application.

**Review by Cireimu — DISMISSED** [review]
Everything looks good so far, the store name font size seems a bit too large, could we try toning that down?
super large name

**Review by mjedwards — COMMENTED** [review]
good

**Review by mjedwards — DISMISSED** [review]

**Pull request merged**
