### PR TITLE
CH--test-fe-Store-Navbar

### PR DESCRIPTION
**Pull request by erferguson**
## Description
Tests written to ensure all image elements for About Us, storeLogo, searchIcon, Cart Icon were rendering in the Store Nav Bar.
## Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/h3ZH5zuQ/133-testing-buyer-store-navbar

### CODE REVIEW

**Comment by bkandaris** [comment]
I think I did a bad job explaining that we need to be testing all (or at least most) elements (divs, links, forms, etc.). Even if you can't 'see' it on the page from a user's point of view. The tests you wrote are great! Good work! Try to cover all of the elements though, please.

**Review by Cireimu — CHANGES_REQUESTED** [review]
Along the same lines as Ben, good job so far, but I'm going to need you to test for visibility of the links in the nav as well as tests to make sure the links are clickable and such I guess. These two mainly come to mind as they are things that I keep seeing getting broken in recent PRs. Great start so far though, everything passes which is good!

**Review by Cireimu — DISMISSED** [review]

**Comment by erferguson** [comment]
Updated and added four new tests per Ben's comments. 

Regarding the clickable links (i.e. the Categories created when adding a new product). These are in a different component (from what I can tell), CategoryPicker.js, className="optionWrapper". 

Should a new branch be created for these tests?

**Review by Cireimu — APPROVED** [review]

**Review by bkandaris — APPROVED** [review]
Nice work using the methods to grab elements!

**Pull request merged**
